- name: Test coverage (upload via covr)
  run: |
    covr::codecov(
      quiet = FALSE,
      token = Sys.getenv("CODECOV_TOKEN")
    )
  shell: Rscript {0}
  env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
